// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PaperModuleScssNamespace {
  export interface IPaperModuleScss {
    paper: string;
  }
}

declare const PaperModuleScssModule: PaperModuleScssNamespace.IPaperModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PaperModuleScssNamespace.IPaperModuleScss;
};

export = PaperModuleScssModule;
